### ISSUE TITLE
Is there a way to create a local patch for a library in DKAN

### ISSUE THREAD

**Issue by achraf-jeday** [GetDKAN/dkan_starter#490]
## Description
This is just a question.

I want to create a local patch for this library: **dkan/libraries/reclineViewNvd3**.
I think patching libraries is not supported in DKAN at the moment. Please correct me if I'm wrong.

Thanks in advance.

**Comment by janette** [comment]
@achraf-jeday 
- Add your patch to the `config/patches/` directory
- Add the override to `config/overrides.make`

```
api: 2
core: 7.x
libraries:
  reclineViewNvd3:
    download:
      type: git
      url: https://github.com/GetDKAN/recline.view.nvd3.js.git
      revision: 7541d7b829e0a725be31790b6457d6068619c2e2
      patch: 
        1: 'patches/[your-patch.patch]'
```
